line-length: { line_length: 250, code_blocks: false, tables: false } # Prefer one sentence per line
no-hard-tabs: { code_blocks: false }
no-inline-html: { allowed_elements: [code, br] } # Allow <code> containing bold text, and tables with <br>
