name: Coverity

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Download Coverity Build Tool
      run: |
        wget https://scan.coverity.com/download/linux64 --post-data "token=$TOKEN&project=nicklauslittle%2Fhorseshoe-j" -O cov-analysis-linux64.tar.gz
        mkdir cov-analysis-linux64
        tar xzf cov-analysis-linux64.tar.gz --strip 1 -C cov-analysis-linux64
      env:
        TOKEN: ${{ secrets.COVERITY_TOKEN }}

    - name: Build with Gradle
      run: |
        export PATH=`pwd`/cov-analysis-linux64/bin:$PATH
        cov-build --dir cov-int ./gradlew build
        tar cjf horseshoe-cov.tar.bz2 cov-int

    - name: Upload Results
      run: |
        export VER=`git describe --tags --match v[0-9]*`
        curl --form token=$TOKEN --form email=nicklaus.little@gmail.com --form file=@horseshoe-cov.tar.bz2 --form version="$VER" --form description="Horseshoe $VER" https://scan.coverity.com/builds?project=nicklauslittle%2Fhorseshoe-j
      env:
        TOKEN: ${{ secrets.COVERITY_TOKEN }}
