name: Coverity

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.3

    - name: Set up JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11

    - name: Download Coverity Build Tool
      run: |
        wget https://scan.coverity.com/download/linux64 --post-data "token=$COVERITY_TOKEN&project=horseshoe" -O cov-analysis-linux64.tar.gz
        mkdir cov-analysis-linux64
        tar xzf cov-analysis-linux64.tar.gz --strip 1 -C cov-analysis-linux64
      env:
        COVERITY_TOKEN: ${{ secrets.COVERITY_TOKEN }}

    - name: Build with Gradle
      run: |
        export PATH=`pwd`/cov-analysis-linux64/bin:$PATH
        cov-build --dir cov-int ./gradlew build
        tar cjf horseshoe-cov.tar.bz2 cov-int

    - name: Upload Results
      run: |
        export VERSION=`git describe --tags --match v[0-9]*`
        curl --form token=$COVERITY_TOKEN --form email=nicklaus.little@gmail.com --form file=@horseshoe-cov.tar.bz2 --form version="$VERSION" --form description="Horseshoe $VERSION" https://scan.coverity.com/builds?project=horseshoe
      env:
        COVERITY_TOKEN: ${{ secrets.COVERITY_TOKEN }}
