name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: "zulu"

    - name: Publish with Gradle
      run: |
        ./gradlew publish
        curl -X POST -H "Authorization: Bearer $(echo -n "$SONATYPE_USER:$SONATYPE_PASSWORD" | base64)" "https://ossrh-staging-api.central.sonatype.com/manual/upload/defaultRepository/com.github.horseshoe"
      env:
        PGP_SIGNING_KEY: ${{ secrets.PGP_SIGNING_KEY }}
        PGP_SIGNING_PASSWORD: ${{ secrets.PGP_SIGNING_PASSWORD }}
        SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_TOKEN }}