name: Release

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.2.0

    - name: Set up JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 11

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload Artifacts
      uses: fnkr/github-action-ghr@v1.3
      env:
        GHR_PATH: build/libs
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker Images
      run: echo ${GITHUB_REF} && rm -rf build && docker build . --file Dockerfile --tag horseshoe/horseshoe --tag horseshoe/horseshoe:${GITHUB_REF/refs\/tags\//}

    - name: Test Docker Image
      run: docker run --rm -t horseshoe/horseshoe

    - name: Push Docker Images
      run: docker login --username horseshoe --password $DOCKERHUB_TOKEN && docker push horseshoe/horseshoe
      env:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
