name: Release

on: release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload JAR
      uses: JasonEtco/upload-to-release@master
      with:
        args: `ls build/libs/horseshoe-*[0-9].jar` application/java-archive
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload JavaDoc JAR
      uses: JasonEtco/upload-to-release@master
      with:
        args: `ls build/libs/horseshoe-*-javadoc.jar` application/java-archive
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Source JAR
      uses: JasonEtco/upload-to-release@master
      with:
        args: `ls build/libs/horseshoe-*-sources.jar` application/java-archive
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
