name: SonarQube

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.3
      with:
        fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11

    - name: Build with Gradle
      run: ./gradlew sonarqube -Dsonar.projectKey=horseshoe_horseshoe -Dsonar.organization=horseshoe -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONARQUBE_TOKEN
      env:
        SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
